[package]
name = "json-gettext"
version = "1.5.0"
authors = ["Magic Len <len@magiclen.org>"]
repository = "https://github.com/magiclen/json-gettext"
homepage = "https://magiclen.org/json-gettext"
keywords = ["json", "i18n", "multi-language", "static"]
categories = ["internationalization"]
description= "A library for getting text from JSON usually for internationalization."
readme = "README.md"
license = "MIT"

[badges]
travis-ci = { repository = "magiclen/json-gettext", branch = "master" }
appveyor = { repository = "magiclen/json-gettext", branch = "master", service = "github" }

[dependencies]
serde = "1.0.72"
serde_json = "1.0.26"
regex = "1"

[features]
nightly = []