name: CI

on: [ push, pull_request ]

env:
  CARGO_TERM_COLOR: always

jobs:
  rustfmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
          components: rustfmt
      - run: cargo fmt -- --check

  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
          components: clippy
      - run: cargo clippy --all-targets -- -D warnings
      - run: cargo clippy --all-targets --features language_region_pair -- -D warnings
      - run: cargo clippy --all-targets --features language -- -D warnings
      - run: cargo clippy --all-targets --features region -- -D warnings

  tests:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        toolchain:
          - nightly
    name: Test ${{ matrix.toolchain }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.toolchain }}
          override: true
      - run: cargo build
      - run: cargo build --examples
      - run: cargo test
      - run: cargo doc
      - run: cargo build --features language_region_pair
      - run: cargo build --examples --features language_region_pair
      - run: cargo test --features language_region_pair
      - run: cargo doc --features language_region_pair
      - run: cargo build --features language
      - run: cargo build --examples --features language
      - run: cargo test --features language
      - run: cargo doc --features language
      - run: cargo build --features region
      - run: cargo build --examples --features region
      - run: cargo test --features region
      - run: cargo doc --features region
      - run: cargo build --features language_region_pair --features rocket
      - run: cargo build --examples --features language_region_pair --features rocket
      - run: cargo test --features language_region_pair --features rocket
      - run: cargo doc --features language_region_pair --features rocket
      - run: cargo build --features language --features rocket
      - run: cargo build --examples --features language --features rocket
      - run: cargo test --features language --features rocket
      - run: cargo doc --features language --features rocket
      - run: cargo build --features region --features rocket
      - run: cargo build --examples --features region --features rocket
      - run: cargo test --features region --features rocket
      - run: cargo doc --features region --features rocket