name: CI

on: [ push, pull_request ]

env:
  CARGO_TERM_COLOR: always

jobs:
  rustfmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
          components: rustfmt
      - run: cargo fmt -- --check

  clippy:
    runs-on: ubuntu-latest
    steps:
      - name: Install ImageMagick
        run: |
          sudo apt update
          sudo apt install libwebp-dev
          wget http://www.imagemagick.org/download/ImageMagick.tar.gz
          tar xf ImageMagick.tar.gz
          mkdir /tmp/ImageMagick-lib
          cd ImageMagick-*
          ./configure --enable-hdri --with-webp
          make
          sudo make install
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
          components: clippy
      - run: cargo clippy -- -D warnings

  tests:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        toolchain:
          - stable
          - nightly
    name: Test ${{ matrix.toolchain }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.toolchain }}
          override: true
      - run: cargo build
      - run: cargo test
      - run: cargo doc
      - run: cargo build --features language_region_pair
      - run: cargo test --features language_region_pair
      - run: cargo doc --features language_region_pair
      - run: cargo build --features language
      - run: cargo test --features language
      - run: cargo doc --features language
      - run: cargo build --features region
      - run: cargo test --features region
      - run: cargo doc --features region
      - run: cargo build --features language_region_pair --features rocket
      - run: cargo test --features language_region_pair --features rocket
      - run: cargo doc --features language_region_pair --features rocket
      - run: cargo build --features language --features rocket
      - run: cargo test --features language --features rocket
      - run: cargo doc --features language --features rocket
      - run: cargo build --features region --features rocket
      - run: cargo test --features region --features rocket
      - run: cargo doc --features region --features rocket